In [1]:
import pandas as pd
from sklearn import preprocessing

In [3]:
path = r"F:\DSBDA\DSBDAL CODES\iris.csv"
col_names = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width', 'Species']

In [4]:
df = pd.read_csv(path, names=col_names)

In [5]:
df.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
print("Missing values in each column:")
df.isnull().sum()

Missing values in each column:

Sepal_Length    0
Sepal_Width     0
Petal_Length    0
Petal_Width     0
Species         0
dtype: int64

In [7]:
df.isnull().sum().sum()

np.int64(0)

In [8]:
df.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
df.shape

(150, 5)

In [10]:
df.dtypes

Sepal_Length    float64
Sepal_Width     float64
Petal_Length    float64
Petal_Width     float64
Species             str
dtype: object

In [11]:
# df['Petal_Length'] = df['Petal_Length'].astype("int")
df.dtypes

Sepal_Length    float64
Sepal_Width     float64
Petal_Length    float64
Petal_Width     float64
Species             str
dtype: object

In [12]:
numeric_cols = ['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width']
x = df[numeric_cols].values.astype(float)

In [13]:
min_max_scaler = preprocessing.MinMaxScaler()

In [14]:
x_scaled = min_max_scaler.fit_transform(x)

In [15]:
df_normalized = pd.DataFrame(x_scaled, columns=numeric_cols)

In [16]:
df_normalized.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0      0.222222     0.625000      0.067797     0.041667
1      0.166667     0.416667      0.067797     0.041667
2      0.111111     0.500000      0.050847     0.041667
3      0.083333     0.458333      0.084746     0.041667
4      0.194444     0.666667      0.067797     0.041667

In [17]:
df['Species'].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [18]:
label_encoder = preprocessing.LabelEncoder()

In [19]:
df['Species'] = label_encoder.fit_transform(df['Species'])

In [20]:
df['Species'].unique()

array([0, 1, 2])

In [ ]:
df.head()

    Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0            5.1          3.5           1.4          0.2        0
1            4.9          3.0           1.4          0.2        0
2            4.7          3.2           1.3          0.2        0
3            4.6          3.1           1.5          0.2        0
4            5.0          3.6           1.4          0.2        0
..           ...          ...           ...          ...      ...
85           6.0          3.4           4.5          1.6        1
86           6.7          3.1           4.7          1.5        1
87           6.3          2.3           4.4          1.3        1
88           5.6          3.0           4.1          1.3        1
89           5.5          2.5           4.0          1.3        1

[90 rows x 5 columns]